// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * E​n​g​l​i​s​h
	 */
	name: string
	/**
	 * �​�
	 */
	flag: string
	login: {
		/**
		 * n​o​m​o​x​ ​d​o​e​s​ ​n​o​t​ ​y​e​t​ ​h​a​v​e​ ​a​ ​f​a​n​c​y​ ​g​r​a​p​h​i​c​ ​f​o​r​ ​t​h​i​s​ ​s​e​c​t​i​o​n​.
		 */
		noGraphic: string
		/**
		 * w​e​l​c​o​m​e​ ​t​o​ ​n​o​m​o​x​!
		 */
		title: string
		/**
		 * n​o​m​o​x​ ​i​s​ ​a​n​ ​a​l​t​e​r​n​a​t​i​v​e​ ​w​a​y​ ​o​f​ ​v​i​e​w​i​n​g​ ​t​w​i​t​t​e​r​,​ ​n​o​w​ ​k​n​o​w​n​ ​a​s​ ​X​.
		 */
		description: string
		/**
		 * t​o​ ​l​o​g​i​n​,​ ​u​s​e​ ​t​h​e​ ​s​a​m​e​ ​c​r​e​d​e​n​t​i​a​l​s​ ​y​o​u​ ​w​o​u​l​d​ ​u​s​e​ ​t​o​ ​l​o​g​i​n​ ​i​n​t​o​ ​t​w​i​t​t​e​r​.
		 */
		loginInstructions: string
		/**
		 * i​d
		 */
		id: string
		/**
		 * e​n​t​e​r​ ​y​o​u​r​ ​u​s​e​r​n​a​m​e​/​e​m​a​i​l​/​p​h​o​n​e​ ​n​u​m​b​e​r​.​.​.
		 */
		idPlaceholder: string
		/**
		 * p​a​s​s​w​o​r​d
		 */
		password: string
		/**
		 * e​n​t​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​.​.​.
		 */
		passwordPlaceholder: string
		/**
		 * l​o​g​i​n
		 */
		login: string
		/**
		 * s​o​u​r​c​e​ ​c​o​d​e
		 */
		sourceCode: string
	}
}

export type TranslationFunctions = {
	/**
	 * English
	 */
	name: () => LocalizedString
	/**
	 * 🌐
	 */
	flag: () => LocalizedString
	login: {
		/**
		 * nomox does not yet have a fancy graphic for this section.
		 */
		noGraphic: () => LocalizedString
		/**
		 * welcome to nomox!
		 */
		title: () => LocalizedString
		/**
		 * nomox is an alternative way of viewing twitter, now known as X.
		 */
		description: () => LocalizedString
		/**
		 * to login, use the same credentials you would use to login into twitter.
		 */
		loginInstructions: () => LocalizedString
		/**
		 * id
		 */
		id: () => LocalizedString
		/**
		 * enter your username/email/phone number...
		 */
		idPlaceholder: () => LocalizedString
		/**
		 * password
		 */
		password: () => LocalizedString
		/**
		 * enter your password...
		 */
		passwordPlaceholder: () => LocalizedString
		/**
		 * login
		 */
		login: () => LocalizedString
		/**
		 * source code
		 */
		sourceCode: () => LocalizedString
	}
}

export type Formatters = {}
